@startuml Composite
page 3x3
package Component {
    abstract class Ad {
        {abstract} +getClientNumber()
    }
}

package Leaf {
    class WeiboAd extends Ad {
        +getClientNumber()
    }
    class WechatAd extends Ad {
        +getClientNumber()
    }
    class WechatAdOther extends WechatAd {
        +getClientNumber()
    }
}
package Composite {
    class Promotion extends Ad {
        -ads: array
        +addAd(Ad $ad)
        +getClientNumber()
    }
}
Ad --o Promotion

note as n1
    1. good for complex tree structure
    2. easy to extend tree
    3. diffcult to provide common interface (aka component)
endnote
@enduml
